// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/app.dart';
import 'api/lan.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiAppInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -837100936;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'remote_bridge',
        ioDirectory: '../../crates/remote-bridge/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiLanCancelSnapshotRequest();

  EngineInfo crateApiAppEngineInfo();

  Future<Uint8List> crateApiLanFetchSnapshot({
    required String address,
    required String hostFingerprint,
  });

  Future<void> crateApiAppInitApp();

  Future<DeviceInfo> crateApiAppInitializeDevice();

  Future<LiveFrame> crateApiLanPollLiveFrame({required int sessionId});

  Future<void> crateApiLanRespondToViewRequest({
    required int requestId,
    required bool approved,
  });

  Future<void> crateApiLanSendLiveInput({
    required int sessionId,
    required int kind,
    required double x,
    required double y,
    required int code,
    required bool pressed,
    required int delta,
  });

  Future<HostStatus> crateApiLanSnapshotHostStatus();

  Future<int> crateApiLanStartLiveSession({
    required String address,
    required String hostFingerprint,
  });

  Future<HostStatus> crateApiLanStartSnapshotHost({required String address});

  Future<void> crateApiLanStopLiveSession({required int sessionId});

  Future<void> crateApiLanStopSnapshotHost();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiLanCancelSnapshotRequest() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanCancelSnapshotRequestConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanCancelSnapshotRequestConstMeta =>
      const TaskConstMeta(debugName: "cancel_snapshot_request", argNames: []);

  @override
  EngineInfo crateApiAppEngineInfo() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_engine_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppEngineInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppEngineInfoConstMeta =>
      const TaskConstMeta(debugName: "engine_info", argNames: []);

  @override
  Future<Uint8List> crateApiLanFetchSnapshot({
    required String address,
    required String hostFingerprint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          sse_encode_String(hostFingerprint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanFetchSnapshotConstMeta,
        argValues: [address, hostFingerprint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanFetchSnapshotConstMeta => const TaskConstMeta(
    debugName: "fetch_snapshot",
    argNames: ["address", "hostFingerprint"],
  );

  @override
  Future<void> crateApiAppInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<DeviceInfo> crateApiAppInitializeDevice() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAppInitializeDeviceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppInitializeDeviceConstMeta =>
      const TaskConstMeta(debugName: "initialize_device", argNames: []);

  @override
  Future<LiveFrame> crateApiLanPollLiveFrame({required int sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_live_frame,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanPollLiveFrameConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanPollLiveFrameConstMeta => const TaskConstMeta(
    debugName: "poll_live_frame",
    argNames: ["sessionId"],
  );

  @override
  Future<void> crateApiLanRespondToViewRequest({
    required int requestId,
    required bool approved,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(requestId, serializer);
          sse_encode_bool(approved, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanRespondToViewRequestConstMeta,
        argValues: [requestId, approved],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanRespondToViewRequestConstMeta =>
      const TaskConstMeta(
        debugName: "respond_to_view_request",
        argNames: ["requestId", "approved"],
      );

  @override
  Future<void> crateApiLanSendLiveInput({
    required int sessionId,
    required int kind,
    required double x,
    required double y,
    required int code,
    required bool pressed,
    required int delta,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(sessionId, serializer);
          sse_encode_u_8(kind, serializer);
          sse_encode_f_32(x, serializer);
          sse_encode_f_32(y, serializer);
          sse_encode_u_32(code, serializer);
          sse_encode_bool(pressed, serializer);
          sse_encode_i_32(delta, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanSendLiveInputConstMeta,
        argValues: [sessionId, kind, x, y, code, pressed, delta],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanSendLiveInputConstMeta => const TaskConstMeta(
    debugName: "send_live_input",
    argNames: ["sessionId", "kind", "x", "y", "code", "pressed", "delta"],
  );

  @override
  Future<HostStatus> crateApiLanSnapshotHostStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_host_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanSnapshotHostStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanSnapshotHostStatusConstMeta =>
      const TaskConstMeta(debugName: "snapshot_host_status", argNames: []);

  @override
  Future<int> crateApiLanStartLiveSession({
    required String address,
    required String hostFingerprint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          sse_encode_String(hostFingerprint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanStartLiveSessionConstMeta,
        argValues: [address, hostFingerprint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanStartLiveSessionConstMeta =>
      const TaskConstMeta(
        debugName: "start_live_session",
        argNames: ["address", "hostFingerprint"],
      );

  @override
  Future<HostStatus> crateApiLanStartSnapshotHost({required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_host_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanStartSnapshotHostConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanStartSnapshotHostConstMeta =>
      const TaskConstMeta(
        debugName: "start_snapshot_host",
        argNames: ["address"],
      );

  @override
  Future<void> crateApiLanStopLiveSession({required int sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanStopLiveSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanStopLiveSessionConstMeta => const TaskConstMeta(
    debugName: "stop_live_session",
    argNames: ["sessionId"],
  );

  @override
  Future<void> crateApiLanStopSnapshotHost() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLanStopSnapshotHostConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanStopSnapshotHostConstMeta =>
      const TaskConstMeta(debugName: "stop_snapshot_host", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DeviceInfo dco_decode_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DeviceInfo(
      fingerprint: dco_decode_String(arr[0]),
      storageDescription: dco_decode_String(arr[1]),
    );
  }

  @protected
  EngineInfo dco_decode_engine_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return EngineInfo(
      version: dco_decode_String(arr[0]),
      platform: dco_decode_String(arr[1]),
      architecture: dco_decode_String(arr[2]),
      protocolMajor: dco_decode_u_32(arr[3]),
      protocolMinor: dco_decode_u_32(arr[4]),
      canConnect: dco_decode_bool(arr[5]),
      canHost: dco_decode_bool(arr[6]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HostStatus dco_decode_host_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return HostStatus(
      listening: dco_decode_bool(arr[0]),
      address: dco_decode_String(arr[1]),
      requestId: dco_decode_u_32(arr[2]),
      peerFingerprint: dco_decode_String(arr[3]),
      deviceName: dco_decode_String(arr[4]),
      live: dco_decode_bool(arr[5]),
      control: dco_decode_bool(arr[6]),
      active: dco_decode_bool(arr[7]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  LiveFrame dco_decode_live_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return LiveFrame(
      frameId: dco_decode_u_32(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      closed: dco_decode_bool(arr[3]),
      error: dco_decode_String(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DeviceInfo sse_decode_device_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fingerprint = sse_decode_String(deserializer);
    var var_storageDescription = sse_decode_String(deserializer);
    return DeviceInfo(
      fingerprint: var_fingerprint,
      storageDescription: var_storageDescription,
    );
  }

  @protected
  EngineInfo sse_decode_engine_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_String(deserializer);
    var var_platform = sse_decode_String(deserializer);
    var var_architecture = sse_decode_String(deserializer);
    var var_protocolMajor = sse_decode_u_32(deserializer);
    var var_protocolMinor = sse_decode_u_32(deserializer);
    var var_canConnect = sse_decode_bool(deserializer);
    var var_canHost = sse_decode_bool(deserializer);
    return EngineInfo(
      version: var_version,
      platform: var_platform,
      architecture: var_architecture,
      protocolMajor: var_protocolMajor,
      protocolMinor: var_protocolMinor,
      canConnect: var_canConnect,
      canHost: var_canHost,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  HostStatus sse_decode_host_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_listening = sse_decode_bool(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_requestId = sse_decode_u_32(deserializer);
    var var_peerFingerprint = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_live = sse_decode_bool(deserializer);
    var var_control = sse_decode_bool(deserializer);
    var var_active = sse_decode_bool(deserializer);
    return HostStatus(
      listening: var_listening,
      address: var_address,
      requestId: var_requestId,
      peerFingerprint: var_peerFingerprint,
      deviceName: var_deviceName,
      live: var_live,
      control: var_control,
      active: var_active,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  LiveFrame sse_decode_live_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_frameId = sse_decode_u_32(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_closed = sse_decode_bool(deserializer);
    var var_error = sse_decode_String(deserializer);
    return LiveFrame(
      frameId: var_frameId,
      width: var_width,
      height: var_height,
      closed: var_closed,
      error: var_error,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_device_info(DeviceInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fingerprint, serializer);
    sse_encode_String(self.storageDescription, serializer);
  }

  @protected
  void sse_encode_engine_info(EngineInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.platform, serializer);
    sse_encode_String(self.architecture, serializer);
    sse_encode_u_32(self.protocolMajor, serializer);
    sse_encode_u_32(self.protocolMinor, serializer);
    sse_encode_bool(self.canConnect, serializer);
    sse_encode_bool(self.canHost, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_host_status(HostStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.listening, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_u_32(self.requestId, serializer);
    sse_encode_String(self.peerFingerprint, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_bool(self.live, serializer);
    sse_encode_bool(self.control, serializer);
    sse_encode_bool(self.active, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_live_frame(LiveFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.frameId, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_bool(self.closed, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
