// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

EngineInfo engineInfo() => RustLib.instance.api.crateApiAppEngineInfo();

/// Runs off the UI thread; the OS credential store may request an unlock.
Future<DeviceInfo> initializeDevice() =>
    RustLib.instance.api.crateApiAppInitializeDevice();

class DeviceInfo {
  final String fingerprint;
  final String storageDescription;

  const DeviceInfo({
    required this.fingerprint,
    required this.storageDescription,
  });

  @override
  int get hashCode => fingerprint.hashCode ^ storageDescription.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceInfo &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          storageDescription == other.storageDescription;
}

class EngineInfo {
  final String version;
  final String platform;
  final String architecture;
  final int protocolMajor;
  final int protocolMinor;
  final bool canConnect;
  final bool canHost;

  const EngineInfo({
    required this.version,
    required this.platform,
    required this.architecture,
    required this.protocolMajor,
    required this.protocolMinor,
    required this.canConnect,
    required this.canHost,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      platform.hashCode ^
      architecture.hashCode ^
      protocolMajor.hashCode ^
      protocolMinor.hashCode ^
      canConnect.hashCode ^
      canHost.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineInfo &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          platform == other.platform &&
          architecture == other.architecture &&
          protocolMajor == other.protocolMajor &&
          protocolMinor == other.protocolMinor &&
          canConnect == other.canConnect &&
          canHost == other.canHost;
}
