// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<HostStatus> startSnapshotHost({
  required String address,
  required String peerFingerprint,
}) => RustLib.instance.api.crateApiLanStartSnapshotHost(
  address: address,
  peerFingerprint: peerFingerprint,
);

Future<HostStatus> snapshotHostStatus() =>
    RustLib.instance.api.crateApiLanSnapshotHostStatus();

Future<void> respondToViewRequest({
  required int requestId,
  required bool approved,
}) => RustLib.instance.api.crateApiLanRespondToViewRequest(
  requestId: requestId,
  approved: approved,
);

Future<void> stopSnapshotHost() =>
    RustLib.instance.api.crateApiLanStopSnapshotHost();

Future<Uint8List> fetchSnapshot({
  required String address,
  required String hostFingerprint,
}) => RustLib.instance.api.crateApiLanFetchSnapshot(
  address: address,
  hostFingerprint: hostFingerprint,
);

Future<void> cancelSnapshotRequest() =>
    RustLib.instance.api.crateApiLanCancelSnapshotRequest();

class HostStatus {
  final bool listening;
  final String address;
  final int requestId;
  final String peerFingerprint;
  final String deviceName;

  const HostStatus({
    required this.listening,
    required this.address,
    required this.requestId,
    required this.peerFingerprint,
    required this.deviceName,
  });

  @override
  int get hashCode =>
      listening.hashCode ^
      address.hashCode ^
      requestId.hashCode ^
      peerFingerprint.hashCode ^
      deviceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostStatus &&
          runtimeType == other.runtimeType &&
          listening == other.listening &&
          address == other.address &&
          requestId == other.requestId &&
          peerFingerprint == other.peerFingerprint &&
          deviceName == other.deviceName;
}
