// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<HostStatus> startSnapshotHost({required String address}) =>
    RustLib.instance.api.crateApiLanStartSnapshotHost(address: address);

Future<HostStatus> snapshotHostStatus() =>
    RustLib.instance.api.crateApiLanSnapshotHostStatus();

Future<void> respondToViewRequest({
  required int requestId,
  required bool approved,
}) => RustLib.instance.api.crateApiLanRespondToViewRequest(
  requestId: requestId,
  approved: approved,
);

Future<void> stopSnapshotHost() =>
    RustLib.instance.api.crateApiLanStopSnapshotHost();

Future<Uint8List> fetchSnapshot({
  required String address,
  required String hostFingerprint,
}) => RustLib.instance.api.crateApiLanFetchSnapshot(
  address: address,
  hostFingerprint: hostFingerprint,
);

Future<void> cancelSnapshotRequest() =>
    RustLib.instance.api.crateApiLanCancelSnapshotRequest();

Future<int> startLiveSession({
  required String address,
  required String hostFingerprint,
}) => RustLib.instance.api.crateApiLanStartLiveSession(
  address: address,
  hostFingerprint: hostFingerprint,
);

Future<LiveFrame> pollLiveFrame({required int sessionId}) =>
    RustLib.instance.api.crateApiLanPollLiveFrame(sessionId: sessionId);

/// kind: 0 motion, 1 button, 2 key, 3 wheel, 4 release held input.
Future<void> sendLiveInput({
  required int sessionId,
  required int kind,
  required double x,
  required double y,
  required int code,
  required bool pressed,
  required int delta,
}) => RustLib.instance.api.crateApiLanSendLiveInput(
  sessionId: sessionId,
  kind: kind,
  x: x,
  y: y,
  code: code,
  pressed: pressed,
  delta: delta,
);

Future<void> stopLiveSession({required int sessionId}) =>
    RustLib.instance.api.crateApiLanStopLiveSession(sessionId: sessionId);

class HostStatus {
  final bool listening;
  final String address;
  final int requestId;
  final String peerFingerprint;
  final String deviceName;
  final bool live;
  final bool control;
  final bool active;

  const HostStatus({
    required this.listening,
    required this.address,
    required this.requestId,
    required this.peerFingerprint,
    required this.deviceName,
    required this.live,
    required this.control,
    required this.active,
  });

  @override
  int get hashCode =>
      listening.hashCode ^
      address.hashCode ^
      requestId.hashCode ^
      peerFingerprint.hashCode ^
      deviceName.hashCode ^
      live.hashCode ^
      control.hashCode ^
      active.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostStatus &&
          runtimeType == other.runtimeType &&
          listening == other.listening &&
          address == other.address &&
          requestId == other.requestId &&
          peerFingerprint == other.peerFingerprint &&
          deviceName == other.deviceName &&
          live == other.live &&
          control == other.control &&
          active == other.active;
}

class LiveFrame {
  final int frameId;
  final int width;
  final int height;
  final bool closed;
  final String error;

  const LiveFrame({
    required this.frameId,
    required this.width,
    required this.height,
    required this.closed,
    required this.error,
  });

  @override
  int get hashCode =>
      frameId.hashCode ^
      width.hashCode ^
      height.hashCode ^
      closed.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveFrame &&
          runtimeType == other.runtimeType &&
          frameId == other.frameId &&
          width == other.width &&
          height == other.height &&
          closed == other.closed &&
          error == other.error;
}
